#spring.application.name=ecommerce_backend
spring:
  application:
    name: Ecommerce Backend

  profiles:
    active:
      - dev

  # database
  datasource:
    url:
    username:
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      connection-timeout: 3000
  #      maximum-pool-size: 3


  #  jpa
  jpa:
    open-in-view: false
    show-sql: false
    hibernate:
      ddl-auto: update

  #  image size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 15MB

  #  log with color
  output:
    ansi:
      enabled: ALWAYS

# api documentation
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080
#  address: 0.0.0.0

logging:
  level:
    org:
      hibernate:
        SQL: debug
        start: debug
        SQL_SLOW: info
        cache: debug
        orm:
          jdbc:
            bind: trace

